### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Grawl** [postcss/sugarss#2]
I see this block comment example in docs:

```sass
/*
 * Multiline comments
 */
```

Is asterisk in each line are required to make it work?

Diff will be more clear if we will modify only two strings instead of each commented string.

This:

```diff
.foo
+    /*
    .bar
        color: red
    .baz
        color: navy
+    */
```

Instead of this:

```diff
.foo
+    /*
-    .bar
-        color: red
-    .baz
-        color: navy
+     * .bar
+     *    color: red
+     * .baz
+     *   color: navy
+     */
```

---

I would prefer to comment by indent also, like:

```sass
.foo
    //.bar
        color: red
    .baz
        color: navy
```

What will be equal to:

```css
.foo {
    /*
    .bar {
        color: red
    }
    */
    .baz {
        color: navy
    }
}
```

It works in that way in [Jade](https://github.com/pugjs/jade) and I very like this way to comment out whole trees.
