### ISSUE TITLE
How to use css-modules?

### ISSUE THREAD

**Issue by comerc** [postcss/sugarss#26]
Please help me. It is does not work:

```
const sugarss = require('sugarss');
postcss(plugins, { parser: sugarss })
```

Error: is not a PostCSS plugin

**Comment by TrySound** [comment]
@comerc Please show full stacktrace or build code.

**Comment by ai** [comment]
@comerc show your full config

**Comment by comerc** [comment]
My changes: [one](https://github.com/comerc/css-modules-demo-meteor-1.3/blob/master/packages/meteor-css-modules/css-modules-processor.js#L5), [two](https://github.com/comerc/css-modules-demo-meteor-1.3/blob/master/packages/meteor-css-modules/css-modules-processor.js#L74)

How to run:

```bash
$ git clone https://github.com/comerc/css-modules-demo-meteor-1.3.git
$ cd css-modules-demo-meteor-1.3
$ npm update
$ meteor
```
...then [http://localhost:3000](http://localhost:3000)

**Comment by ai** [comment]
Sorry, I don’t now meteor and all other code there. You should ask better guys :).

Or maybe you can simplify your config by using [postcss-modules](https://github.com/outpunk/postcss-modules)? It brings CSS Modules back to PostCSS pipeline, so you don’t need a lot of code like in that example.

**Comment by comerc** [comment]
reconstruction
```
const sugarss = require('sugarss');
const sorting = require('postcss-sorting');
const postcss = require('postcss');
let s = `
.test
	color: red
`;
postcss([sorting], { parser: sugarss }).process(s).then(function (result) {
	console.log('test', result.content);
});
```
is not a PostCSS plugin at Processor.normalize (/postcss/lib/processor.js:60:23)

**Comment by ben-eb** [comment]
The *parser* option needs to be set in the *process* call, as the second argument.

**Comment by lagden** [comment]
@ai or @outpunk or @markdalgleish

I am using sugarss + postcss-modules!
The problem is when I try use `composes` with `sss`

You can see on example below that `xxx` is not composed correctly... `-> undefined`

Is there any way for this to work?

**Example**

```styl
// theme.sss
.xxx
	border-radius: 5px
```

```styl
// home.sss
@import '../../shared/vars.sss'

.root
	composes: xxx from '../../shared/theme.sss'
	background: green
	color: niceGray
	&_big
		width: 50em
		@media (--mobile)
			width: auto

```

```css
/* home.css */
.xxx: 5px;
._root_1hilm_3 {
	background: green;
	color: #777;
}
._root_big_1hilm_1 {
	width: 50em;
}
@media (max-width: 640px) {
	._root_big_1hilm_1 {
		width: auto;
	}
}
```
 
```js
// home.json
{"niceGray":"#777","root":"_root_1hilm_3 undefined","root_big":"_root_big_1hilm_1"}
```

**Comment by lagden** [comment]
I making a workaround using `@import`, but is staying dirty!!

The `useless` comes to inflate!! 😞 

```styl
// vars.sss
@value niceGray: #777
@custom-media --mobile (max-width: 640px)

.fromImport
	border: 1px solid red

.useless
	color: blue
```

```styl
// home.sss
.root
	composes: fromImport
	background: green
	color: niceGray
	&_big
		width: 50em
		@media (--mobile)
			width: auto
```

```css
/* home.css */
._fromImport_f2hie_1 {
	border: 1px solid red;
}
._useless_f2hie_1 {
	color: blue;
}
._root_f2hie_3 {
	background: green;
	color: #777;
}
._root_big_f2hie_1 {
	width: 50em;
}
@media (max-width: 640px) {
	._root_big_f2hie_1 {
		width: auto;
	}
}
```
