### ISSUE TITLE
Indent dependent block comments

### ISSUE THREAD

**Issue by Grawl** [postcss/sugarss#3]
I would prefer to comment by indent.

```sass
.foo
    //.bar
        color: red
    .baz
        color: navy
```

What will be equal to:

```css
.foo {
    /*
    .bar {
        color: red
    }
    */
    .baz {
        color: navy
    }
}
```

It works in that way [in Jade](http://jade-lang.com/reference/comments/) and I very like this way to comment out whole trees.
