### ISSUE TITLE
How to loop with a var?

### ISSUE THREAD

**Issue by corysimmons** [postcss/sugarss#43]
With precss I can:

```scss
@for $i from 1 to 6 {
  &:nth-child($(i)) {
    width: myPostCSSPlugin(1 2 3)[$(i)];
  }
}
```

But I can't figure out how to do this with sugarss. SugarSS have official API docs anywhere?

**Comment by ai** [comment]
You need to add PreCSS (pack of PostCSS plugins for mixins/loops and other preprocessor stuff)

https://github.com/jonathantneal/precss

SugarSS is just a syntax. It have no any other magic.

**Comment by corysimmons** [comment]
What's the syntax for `for` loops in SugarSS?

I tried

```styl
.stylus-syntax
  for $i in 1..6
    width: $i
```

and

```scss
.scss-syntax {
  @for $i from 1 to 6 {
    width: $i;
  }
}
```

I also tried these with the `$i` wrapped like precss prefers `$(i)` to no avail.

**Comment by ai** [comment]
Let’s start from basis:

1. SugarSS has no any features. It is a syntax to write CSS and CSS-like files. With any features. SugarSS doesn’t unwrap nested rules. It doesn’t compile variables, etc. It only parse properties, rules and at-rules.
2. But PostCSS has other plugins to compile variables, loops and nested rules.
3. There is a [PreCSS](https://github.com/jonathantneal/precss) plugins pack with all preprocessors like features.
4. You can use PreCSS (or any other PostCSS plugin) with SugarSS.
5. PreCSS has `@each` and `@for` loops. There is no special *syntax* for them. They just custom at-rule.

**Comment by ai** [comment]
So, if you want to do loop:

1. You should go to [PreCSS](https://github.com/jonathantneal/precss) repo and find loop plugin syntax:

```css
@each $icon in (foo, bar, baz) {
    .icon-$(icon) {
        background: url('icons/$(icon).png');
    }
}
```

2. This example is in CSS. You need to convert it to SugarCSS. It is easy, because it is just at-rule with `each` name:

```css
@each $icon in (foo, bar, baz)
    .icon-$(icon)
        background: url('icons/$(icon).png')
```
