### ISSUE TITLE
Last declaration is missing semicolon

### ISSUE THREAD

**Issue by michael-ciniawsky** [postcss/sugarss#57]
```
.a 
  color: red
```

```css
.a {
  color: red // <= 
}
```

```
.a
  color: red
  background-color: white
```

```css
.a {
  color: red; // ok
  background-color: white // <=
}
```

It's happens only on the last decl of a certain block. It's seems to be valid according to [CSS 2.2](https://www.w3.org/TR/CSS2/syndata.html#declaration), is it intensionally ? :)
