### ISSUE TITLE
All-in-one Sass Replacement?

### ISSUE THREAD

**Issue by TheJaredWilcurt** [postcss/sugarss#79]
Curious if there is a single `npm install` that can take this:
```stylus
$brandColor: #F00
$mainWdith: 600px

.parent
    display: grid
    grid-template-areas: 
      'header  header  header'
      'sidebar content ad'
      'sidebar footer  footer'
    .child
        background: $brandColor
        width: $mainWidth + 200
        box-shadow:
          1px 1px 1px #F00,
          2px 2px 2px #00F
```
and produce
```css
.parent {
    display: grid;
    grid-template-areas: 'header  header  header' 'sidebar content ad' 'sidebar footer  footer';
}
.parent .child {
    background: #F00;
    width: 800px;
    box-shadow: 1px 1px 1px #F00, 2px 2px 2px #00F;
}
```
I've seen most of this covered as individual Post-CSS plugins, but haven't seen an "all-in-one" Sass replacement that is easier to set up than the real thing. If you add in the ability to do linting, then I'd be interested in swapping Sass out for it in personal projects. Then maybe building tooling around it and contributing. Right now I've been using Sass for so long I can't reasonably justify leaving it to do more work for less features.
